AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys a lambda functon that generates Self-Signed SSL Certificate and its private key.  The artifact is added to the SSM Parameter Stores"
##############################################################################
#                               Resources                                    #
##############################################################################
Resources:
  certGenLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: certGen_Lambda
      Handler: lambda_function.lambda_handler
      Role:
        'Fn::GetAtt':
          - certGenLambdaIamRole
          - Arn
      Runtime: python3.7
      Timeout: 900
      Code:
        S3Bucket: rancher-qs-eks-lambdazip-ca-central
        S3Key: function.zip

  certGenLambdaIamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: genCert_Lambda_Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: putSsmParametersAllow
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: putssmparamallow
                Effect: Allow
                Action:
                  - ssm:PutParameter
                Resource:
                  - "arn:aws:ssm:*:*:parameter/*"
